#!/bin/bash
# script to install and setup nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sed -i 's/listen\s*80;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.nginx-debian.html
