#!/usr/bin/env bash
#Install Nginx and configure it

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.linkedin.com/in/thy-macharia-66b609161;" /etc/nginx/sites-enabled/default

sudo service nginx restart

