#!/usr/bin/env bash
#Editing the default config file

sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.facebook.com/bwemty/videos/gta-5-pani-moments/662669848412794/;\n	}' /etc/nginx/sites-available/default
sudo service nginx restart
