#!/usr/bin/env bash
#Install nginx & configure

sudo apt-get update
sudo apt-get -y install nginx

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://https://www.facebook.com/bwemty/videos/gta-5-pani-moments/662669848412794/ permanent;" /etc/nginx/sites-available/default

sudo service nginx restart

