#!/usr/bin/env bash

# Create custom 404 page
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

# Add configuration to Nginx default file
sudo sed -i '/server {/a error_page 404 /404.html;\nlocation = /404.html {\ninternal;\n}\n' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
