#!/usr/bin/env bash
# Script that doubles the number of webservers and adds new configs
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get -y install nginx
string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";\n"
sudo sed -i "s/http {/$string/" /etc/nginx/nginx.conf

sudo service nginx restart

