#!/usr/bin/env bash
#This script installs and starts Nginx

#Update package information
sudo apt-get update

#Install Nginx
sudo apt-get install -y nginx

#Check if Nginx is running
if ! pgrep nginx >/dev/null; then
    # Start Nginx if it is not running
    sudo service nginx start
fi
