#!/usr/bin/env bash
: '
A Bash script that displays a list of currently running processes.

Requirements:

Must show all processes, for all users, including those which might not have a TTY
Display in a user-oriented format
Show process hierarchy
'

# Print header row
printf "%-8s %-5s %-5s %-6s %-6s %-5s %-7s %-6s %-11s %s\n" \
  "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "COMMAND"

# Loop through each process
while read -r user pid cpu mem vsz rss tty stat start time command; do
  # Print each process with specified format
  printf "%-8s %-5s %-5s %-6s %-6s %-5s %-7s %-6s %-11s %s\n" \
    "$user" "$pid" "$cpu" "$mem" "$vsz" "$rss" "$tty" "$stat" "$start" "$command"
done < <(ps aux)

# Display process hierarchy
pstree -p

