#!/usr/bin/env bash
# A bash script that displays a list of currently running processes.

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | sed 's/$/ /' | sed 's/^ *//'

