#!/usr/bin/env bash
: "
Write a Bash script that displays numbers from 1 to 100.

Requirements:

Displays FizzBuzz when the number is a multiple of 3 and 5
Displays Fizz when the number is multiple of 3
Displays Buzz when the number is a multiple of 5
Otherwise, displays the number
In a list format
"

counter=1

for counter in {1..100}
do
	if [ $((counter % 3)) -eq 0 ] && [ $((counter % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((counter % 3 )) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((counter % 5 )) -eq 0 ]
        then
                echo "Buzz"
        else 
		echo "$counter"
	fi
done
