#!/usr/bin/env bash
: "
A Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
"

counter=0

while [ "$counter" -le 9 ]
do
	if [ "$counter" -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done

