#!/usr/bin/env bash
#A Bash script that displays the time for 12 hours and 59 minutes:

#display hours from 0 to 12
#display minutes from 1 to 59

hour=0

while [ "$hour" -lt 12 ]
do
    if [ "$hour" -eq 0 ]
    then
        echo "Hour: 12"
    else
        echo "Hour: $hour"
    fi
    
    minute=0
    while [ "$minute" -lt 60 ]
    do
        if [ "$minute" -lt 10 ]
        then
            echo "$minute"
        else
            echo "$minute"
        fi
        ((minute++))
    done
    ((hour++))
done
