#!/usr/bin/env bash
#A Bash script that gives you information about the school file.

#Requirements:

#You must use if and, else (case is forbidden)
#Your Bash script should check if the file exists and print:
#if the file exists: school file exists
#if the file does not exist: school file does not exist
#If the file exists, print:
#if the file is empty: school file is empty
#if the file is not empty: school file is not empty
#if the file is a regular file: school is a regular file
#if the file is not a regular file: (nothing)

filename="School"

if [ -e "$filename" ]
then
	echo "School file exists"
	if [ -s "$filename" ]
	then
		echo "School file is not empty"
	else
		echo "School file is empty"	
	fi

	if [ -f "$filename" ]
	then
		echo "School is a regular file"
	else
		echo ""
	fi
else
	echo "School file does not exist"
fi

