#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user

sed -i 's/user\s*[^;]*;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*[^;]*;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart

